server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/demo/**
        - id: ANOTHER-SERVICE
          uri: http://localhost:9091
          predicates:
              - Path=/another/**

  main:
    web-application-type: reactive